version: '3.8'

networks:
  microservice-network:
    external:
      name: microservice-network

volumes:
  app-data:

services:

  nginx-gateway:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservice-network
